version: "3"
services:
  kafka:
    container_name: kafka-test
    image: 'bitnami/kafka:3.2.3'
    ports:
      - '9092:9092' 
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_AUTO_COMMIT_OFFSET=false
  
  go-app:
    container_name: go-kafka-test
    build: go 
    ports:
      - 3000:3000
    environment:
      - PORT=3000
    volumes: 
      - ./go:/src

  python-app:
    container_name: python-kafka-test
    build: python 
    ports:
      - 5000:5000 
    volumes: 
      - ./python:/src